### ISSUE TITLE
Relog

### ISSUE THREAD

**Issue by mperroy** [tlanvaldear/RMA-2k16#1]
Pour la fonction relog, ce n'est pas juste la reconnexion (me.connect(...)), parce qu'il n'y a pas besoin de plus d'info du coup, puisque le socket client n'est pas fermé ?

**Comment by tlanvaldear** [comment]
Le problème, c'est que rappeler me.connect() alors qu'il est pas refermé sort l'erreur de connection.
À vérifier avec un close() connect() si ça change.
Je pense que c'est surtout du coté host que il va y avoir a changer deux trois choses de manière a ce que host n'attende pas des clients nouveaux a chaque fois.

**Comment by mperroy** [comment]
Dans client.py, dans la fonction me_player, pour le me.connect(argv[1],4402), ce n'est pas plutôt argv[0].
C'est la question que je me pose car lorsque je tente de le lancer je me trouve face à une erreur sur l'index(out of range). 
Peut être que c'est moi aussi qui fait mal, je lance le client sans arguments, on est d'accord que c'est le localhost en faisant ça ?

**Comment by mperroy** [comment]
Je viens de voir un petit bug,
Séquence de jeu: 
J1: 0 4(bug assertion error (dans grid.py ligne 18))
J2: 0 4

**Comment by mperroy** [comment]
Désolé pour les commits, je n'avais vu que que c'était fait exprès.

**Comment by tlanvaldear** [comment]
Quote:
```
Dans client.py, dans la fonction me_player, pour le me.connect(argv[1],4402), ce n'est pas plutôt argv[0].
C'est la question que je me pose car lorsque je tente de le lancer je me trouve face à une erreur sur l'index(out of range).
Peut être que c'est moi aussi qui fait mal, je lance le client sans arguments, on est d'accord que c'est le localhost en faisant ça ?
```
Pour l'instant, pour se connecter a localhost, il faut préciser `''` ou localhost (bien que localhost ne soit pas du tout apprécié en python...)
Sans argument, `argv[1]` n'a aucune valeur et `argv[0] = ./client.py`

**Comment by mperroy** [comment]
Oui oui j'ai compris, c'est pour ça que j'ai supprimé mes commentaires ^^

**Comment by mperroy** [comment]
Sa te dit demain aprèm, on va au cremi pour bosser tous les deux ?

**Comment by tlanvaldear** [comment]
Oui, ça peut se faire
J'ai quelque chose à faire en fin d'après midi (16hrs timelimit), mais on peut faire ça avant sans souci

j'arriverai a 11 heures sur le campus je pense, pour prendre de quoi manger

**Comment by tlanvaldear** [comment]
Je suis posé en 008 !

**Comment by mperroy** [comment]
Sa marche, je finis de manger et je me ramène ^^

**Comment by tlanvaldear** [comment]
https://discord.gg/FW2tXrR
