### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by tlanvaldear** [tlanvaldear/RMA-2k16#3]
le lien pour l'overleaf :https://www.overleaf.com/7642634dczcszbddzvy

**Comment by mperroy** [comment]
Ah ben assez rapide, je viens de le faire aussi xD

**Comment by tlanvaldear** [comment]
Je vais commit une dernière édition sur les socket, on utilisait ipv6 ce qui limitait notre quantité d'host !

**Comment by mperroy** [comment]
Maudit ipv6 !

**Comment by tlanvaldear** [comment]
Encore un, si on ctrl+c les deux clients, il faut redémarrer !

**Comment by mperroy** [comment]
Sa marche !

**Comment by mperroy** [comment]
Et bien je crois que c'est bon pour ce rapport aussi.
Je viens de relire pour les fautes, etc ...

**Comment by tlanvaldear** [comment]
append(host) permet juste de réinitialiser la liste client_select, qui doit contenir host au début
Maintenant on appelle juste restart() qui fait le boulot!

**Comment by mperroy** [comment]
Ah ! Mince

**Comment by mperroy** [comment]
C'est modifié dans le rapport

**Comment by tlanvaldear** [comment]
Bon, bah du coup c'est fini là aussi
Je te laisse l'envoyer au prof ?

**Comment by mperroy** [comment]
Parfait, je m'en occupe yep
