### ISSUE TITLE
AAAAAAAAAAAAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by tlanvaldear** [tlanvaldear/RMA-2k16#4]
On doit passer tout ce qu'on a fait sur un fichier .py
source: mail

**Comment by mperroy** [comment]
Je viens de voir ça ....

**Comment by tlanvaldear** [comment]
j'ai commit le main du coup, plus qu'à retaper les lignes sur le rapport !

**Comment by mperroy** [comment]
J'avais quasi fini aussi ^^
Aller go rapport pour la seconde fois

**Comment by mperroy** [comment]
Tu as vérifié que cela marchait toujours ?

**Comment by tlanvaldear** [comment]
Oui, c'est juste un rename des fonction main() respectives, et tout est bon

**Comment by mperroy** [comment]
Oui oui mais on s'est jamais, il vaut mieux vérifier ;)

**Comment by tlanvaldear** [comment]
j'ai bien vérifié c'est ce que j'entendais par "tout est bon"

**Comment by mperroy** [comment]
Pas de souci, bon ben je crois que c'est tout bon cette fois

**Comment by mperroy** [comment]
C'est bon de ton côté aussi ?

**Comment by tlanvaldear** [comment]
ça a l'air :)

**Comment by mperroy** [comment]
Aller je renvois le mail !
